In [7]:
import numpy as np
import pandas as pd

#### Select all the correct tags submitted by users to "Matrix, The (1999)" movie?

In [25]:
# Store the given tags as a list
tags = ["alternate universe", "karate", "philosophy", "post apocalyptic"]

# Correct tags for "Matrix, The (1999)" based on your understanding
correct_tags = ["alternate universe", "philosophy", "post apocalyptic"]

# Select the correct tags from the given list
selected_tags = [tag for tag in tags if tag in correct_tags]

# Print the selected tags
print("Selected tags:", selected_tags)

Selected tags: ['alternate universe', 'philosophy', 'post apocalyptic']

## Important note1

In [35]:
A= pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\ratings.csv")
A

        userId  movieId  rating   timestamp
0            1        1     4.0   964982703
1            1        3     4.0   964981247
2            1        6     4.0   964982224
3            1       47     5.0   964983815
4            1       50     5.0   964982931
...        ...      ...     ...         ...
100831     610   166534     4.0  1493848402
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352
100835     610   170875     3.0  1493846415

[100836 rows x 4 columns]

In [36]:
B = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\movies.csv")
B

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
9737,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy
9738,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy
9739,193585,Flint (2017),Drama
9740,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation
9741,193609,Andrew Dice Clay: Dice Rules (1991),Comedy

In [40]:
import pandas as pd

# Assuming you have loaded the ratings and movies data into DataFrames
# Replace these with your actual data loading steps
ratings = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\ratings.csv")  # Assuming you have a ratings CSV file
movies = pd.read_csv(r'C:\Users\Administrator\Downloads\movie_data\movies.csv')    # Assuming you have a movies CSV file

# Step 1: Group ratings by movieId and calculate count and mean
ratings_grouped = ratings.groupby('movieId')['rating'].agg(['count', 'mean']).reset_index()

# Step 2: Inner join with the movies DataFrame
merged_data = pd.merge(movies, ratings_grouped, on='movieId', how='inner')

# Step 3: Filter movies with more than 50 user ratings
filtered_movies = merged_data[merged_data['count'] > 50]

# List of movies to check for popularity
movies_to_check = ["Godfather, The (1972)", "Shawshank Redemption, The (1994)", "Jumanji (1995)", "Wolf of Wall Street, The (2013)"]

# Filter movies among the given options
popular_movies = filtered_movies[filtered_movies['title'].isin(movies_to_check)]

# Find the most popular movie based on average user ratings
most_popular = popular_movies.nlargest(1, 'mean')

# Print the most popular movie based on average user ratings
print("Most popular movie based on average user ratings:")
print(most_popular[['title', 'mean']])

Most popular movie based on average user ratings:
                                title      mean
277  Shawshank Redemption, The (1994)  4.429022

In [42]:
import pandas as pd

# Assuming you have loaded the ratings and movies data into DataFrames
# Replace these with your actual data loading steps
ratings = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\ratings.csv")  # Assuming you have a ratings CSV file
movies = pd.read_csv(r'C:\Users\Administrator\Downloads\movie_data\movies.csv')    # Assuming you have a movies CSV file

# Step 1: Group ratings by movieId and calculate count and mean
ratings_grouped = ratings.groupby('movieId')['rating'].agg(['count', 'mean']).reset_index()

# Step 2: Inner join with the movies DataFrame
merged_data = pd.merge(movies, ratings_grouped, on='movieId', how='inner')

# Step 3: Filter movies with more than 50 user ratings
filtered_movies = merged_data[merged_data['count'] > 50]

# List of movies to check for popularity
movies_to_check = ["Pulp Fiction (1994)", "Bad Boys (1995)", "Silence of the Lambs, The (1991)", "Matrix, The (1999)"]

# Filter movies among the given options
popular_movies = filtered_movies[filtered_movies['title'].isin(movies_to_check)]

# Sort by number of user ratings in descending order
top_5_popular = popular_movies.nlargest(5, 'count')

# Print the top 5 popular movies based on number of user ratings
print("Top 5 popular movies based on number of user ratings:")
print(top_5_popular[['title', 'count']])

Top 5 popular movies based on number of user ratings:
                                 title  count
257                Pulp Fiction (1994)    307
510   Silence of the Lambs, The (1991)    279
1938                Matrix, The (1999)    278
118                    Bad Boys (1995)     51

In [43]:
import pandas as pd

# Assuming you have loaded the ratings and movies data into DataFrames
# Replace these with your actual data loading steps
ratings = pd.read_csv(r'C:\Users\Administrator\Downloads\movie_data\ratings.csv')  # Assuming you have a ratings CSV file
movies = pd.read_csv(r'C:\Users\Administrator\Downloads\movie_data\movies.csv')    # Assuming you have a movies CSV file

# Step 1: Group ratings by movieId and calculate count and mean
ratings_grouped = ratings.groupby('movieId')['rating'].agg(['count', 'mean']).reset_index()

# Step 2: Inner join with the movies DataFrame
merged_data = pd.merge(movies, ratings_grouped, on='movieId', how='inner')

# Step 3: Filter movies with more than 50 user ratings
filtered_movies = merged_data[merged_data['count'] > 50]

# List of Sci-Fi movies to check for popularity
sci_fi_movies = ["Deadpool (2016)", "Terminator 2: Judgment Day (1991)", "X-Men: The Last Stand (2006)", "Jurassic Park (1993)"]

# Filter Sci-Fi movies among the given options
sci_fi_movies_data = filtered_movies[filtered_movies['title'].isin(sci_fi_movies)]

# Sort by number of user ratings in descending order
sorted_sci_fi_movies = sci_fi_movies_data.nlargest(len(sci_fi_movies_data), 'count')

# Get the third most popular Sci-Fi movie
third_most_popular_sci_fi = sorted_sci_fi_movies.iloc[2]

# Print the third most popular Sci-Fi movie based on number of user ratings
print("Third most popular Sci-Fi movie based on number of user ratings:")
print(third_most_popular_sci_fi[['title', 'count']])

Third most popular Sci-Fi movie based on number of user ratings:
title    Deadpool (2016)
count                 54
Name: 8673, dtype: object

## Important note 2

In [52]:
import pandas as pd

# Load movies.csv, ratings.csv, and links.csv into DataFrames
movies_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\movies.csv")
ratings_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\ratings.csv")
links_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\links.csv")

# Merge movies and links to get IMDb IDs
movies_links = pd.merge(movies_df, links_df[['movieId', 'imdbId']], on='movieId', how='inner')

# Count the number of ratings for each movie
ratings_count = ratings_df.groupby('movieId').size().reset_index(name='num_ratings')

# Filter movies with more than 50 user ratings
movies_over_50_ratings = movies_links.merge(ratings_count[ratings_count['num_ratings'] > 50], on='movieId', how='inner')

# Find the movie with the highest IMDb rating among movies with over 50 ratings
highest_rated_movie = movies_over_50_ratings.loc[movies_over_50_ratings['imdbId'].idxmax()]

highest_rated_movie_id = highest_rated_movie['movieId']

print(f"The movieId of the movie with the highest IMDb rating and more than 50 user ratings is: {highest_rated_movie_id}")

The movieId of the movie with the highest IMDb rating and more than 50 user ratings is: 109374

In [53]:
import pandas as pd

# Load movies.csv, ratings.csv, and links.csv into DataFrames
movies_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\movies.csv")
ratings_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\ratings.csv")
links_df = pd.read_csv(r"C:\Users\Administrator\Downloads\movie_data\links.csv")

# Merge movies and links to get IMDb IDs
movies_links = pd.merge(movies_df, links_df[['movieId', 'imdbId']], on='movieId', how='inner')

# Count the number of ratings for each movie
ratings_count = ratings_df.groupby('movieId').size().reset_index(name='num_ratings')

# Merge movies with more than 50 ratings and links to get Sci-Fi movies with IMDb IDs
scifi_movies = movies_links.merge(ratings_count[ratings_count['num_ratings'] > 50], on='movieId', how='inner')
scifi_movies = scifi_movies[scifi_movies['genres'].str.contains('Sci-Fi', case=False)]

# Find the Sci-Fi movie with the highest IMDb rating
highest_rated_scifi_movie = scifi_movies.loc[scifi_movies['imdbId'].idxmax()]

highest_rated_scifi_movie_id = highest_rated_scifi_movie['movieId']

print(f"The movieId of the Sci-Fi movie with the highest IMDb rating and more than 50 user ratings is:{highest_rated_scifi_movie_id}")

The movieId of the Sci-Fi movie with the highest IMDb rating and more than 50 user ratings is:112852